version: "3.7"

services:
  mongodb:
    image: mongo:latest
    container_name: task-mongodb
    networks:
      - my-net
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: tododb
    ports:
      - 27017:27017
    volumes:
      - ./task-mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  task-ui:
    image: task-ui
    container_name: task-ui-todo
    networks:
      - my-net
    restart: always
    ports:
      - 8080:8080

networks:
  my-net:
    driver: bridge
