apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-mongo
  labels:
    app: task-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-mongo
  template:
    metadata:
      labels:
        app: task-mongo
    spec:
      containers:
        - name: task-mongo
          image: mongo:latest
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"
            - name: MONGO_INITDB_DATABASE
              value: "todoapp"
          ports:
            - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: task-mongo
spec:
  selector:
    app: task-mongo
  ports:
    - port: 27017
      targetPort: 27017
